# check-ui.py
"""Static checks on the app shell that a syntax check cannot catch.

Run from the project folder:

    python3 check-ui.py

Verifies:

1. Every element id referenced from app.js via $('id') exists in index.html
   (or is generated by app.js itself).
2. Elements toggled with the `hidden` attribute are actually hidden. The
   browser's [hidden] rule loses to any author rule that sets `display`, so a
   `.modal { display: flex }` element stays on screen forever with the
   attribute set. A global `[hidden] { display: none !important }` is
   required; without it a scrim can cover the whole app.
3. Nothing carries the hidden attribute without a matching show/hide path.

Exits non-zero on failure so it can gate a release.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
HTML = (HERE / "index.html").read_text()
CSS = (HERE / "app.css").read_text()
JS = (HERE / "app.js").read_text()

failures: list[str] = []


def fail(msg: str) -> None:
    """Record a failed check."""
    failures.append(msg)
    print(f"FAIL  {msg}")


def ok(msg: str) -> None:
    """Record a passed check."""
    print(f"ok    {msg}")


# --- 1. every $('id') resolves ---------------------------------------------

refs = set(re.findall(r"\$\('([^']+)'\)", JS))
static_ids = set(re.findall(r'id="([^"]+)"', HTML))
dynamic_ids = set(re.findall(r'id="([a-zA-Z][\w-]*)"', JS))
missing = sorted(refs - static_ids - dynamic_ids)

if missing:
    fail(f"app.js references ids that do not exist: {', '.join(missing)}")
else:
    ok(f"all {len(refs)} referenced element ids resolve")


# --- 2. the hidden attribute must win --------------------------------------

GLOBAL_HIDDEN = re.compile(r"\[hidden\]\s*\{[^}]*display\s*:\s*none\s*!important", re.S)

if GLOBAL_HIDDEN.search(CSS):
    ok("global [hidden] { display: none !important } present")
else:
    fail(
        "no global [hidden] { display: none !important } rule - any component "
        "styled with `display` will ignore the hidden attribute and stay on screen"
    )

# Report which hidden elements would break without that rule, so the risk is
# visible even when the guard is in place.
hidden_els = re.findall(r'<[^>]*\bid="([^"]+)"[^>]*\bclass="([^"]*)"[^>]*\bhidden\b', HTML)
display_classes = {
    cls
    for cls, body in re.findall(r"\.([\w-]+)\s*\{([^}]*)\}", CSS)
    if re.search(r"(^|;)\s*display\s*:", body)
}

at_risk = [
    (el_id, cls)
    for el_id, classes in hidden_els
    for cls in classes.split()
    if cls in display_classes
]
if at_risk:
    listed = ", ".join(f"#{i} (.{c})" for i, c in at_risk)
    ok(f"{len(at_risk)} hidden element(s) depend on the global rule: {listed}")
else:
    ok("no hidden element sets display via a class")


# --- 3. hidden elements are toggled somewhere ------------------------------

unreferenced = [
    el_id
    for el_id, _classes in hidden_els
    if f"'{el_id}'" not in JS and f'"{el_id}"' not in JS
]
if unreferenced:
    for el_id in unreferenced:
        fail(f"#{el_id} starts hidden but app.js never references it")
else:
    ok("every hidden element has a show path in app.js")


# --- 4. version strings agree ----------------------------------------------

app_ver = re.search(r"APP_VERSION\s*=\s*'([^']+)'", JS)
sw_ver = re.search(r"CACHE_VERSION\s*=\s*'([^']+)'", (HERE / "sw.js").read_text())
json_ver = re.search(r'"version"\s*:\s*"([^"]+)"', (HERE / "version.json").read_text())


def norm(match: re.Match | None) -> str | None:
    """Normalize a version string, tolerating a leading 'v'."""
    return match.group(1).lstrip("v") if match else None


vals = {
    "app.js APP_VERSION": norm(app_ver),
    "sw.js CACHE_VERSION": norm(sw_ver),
    "version.json version": norm(json_ver),
}
if len(set(vals.values())) == 1 and None not in vals.values():
    ok(f"version strings agree ({vals['app.js APP_VERSION']})")
else:
    fail(f"version strings disagree: {vals} - updates will not install cleanly")


print()
if failures:
    print(f"{len(failures)} FAILURE(S)")
    sys.exit(1)
print("ALL UI CHECKS PASSED")
