# check-ui.py
"""Static checks on the app shell that a syntax check cannot catch.

    python3 check-ui.py

Verifies:

1. Every element id referenced from JS via $('id') exists in index.html or is
   generated by the JS itself.
2. A global `[hidden] { display: none !important }` rule is present. Without
   it, any element styled with `display` ignores the hidden attribute - which
   renders modals as permanent full-screen overlays that block every tap.
3. Every tab and extra screen declared in config.js has a matching section.
4. The version strings in config.js, sw.js and version.json agree; a mismatch
   stops updates installing.
5. Every same-directory JS module is listed in the service worker PRECACHE,
   or it will be missing offline.

Exits non-zero on failure so it can gate a release.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

HTML = (HERE / "index.html").read_text()
CSS = (HERE / "app.css").read_text()
CONFIG = (HERE / "config.js").read_text()
SW = (HERE / "sw.js").read_text()
JS = "\n".join(p.read_text() for p in sorted(HERE.glob("*.js")) if p.name != "sw.js")

failures: list[str] = []


def fail(msg: str) -> None:
    """Record a failed check."""
    failures.append(msg)
    print(f"FAIL  {msg}")


def ok(msg: str) -> None:
    """Record a passed check."""
    print(f"ok    {msg}")


# --- 1. every $('id') resolves ---------------------------------------------

refs = set(re.findall(r"\$\('([^']+)'\)", JS))
refs |= {m.replace("${level}", "0") for m in re.findall(r"\$\(`([^`]+)`\)", JS)}
refs = {r for r in refs if "${" not in r}
static_ids = set(re.findall(r'id="([^"]+)"', HTML))
dynamic_ids = set(re.findall(r'id="([a-zA-Z][\w-]*)"', JS))
missing = sorted(refs - static_ids - dynamic_ids)

if missing:
    fail(f"JS references ids that do not exist: {', '.join(missing)}")
else:
    ok(f"all {len(refs)} referenced element ids resolve")

# Template-literal sheet ids: verify both layers exist in the HTML.
for level in (0, 1):
    for part in ("", "Title", "Body", "Close"):
        el = f"sheet{level}{part}"
        if f'id="{el}"' not in HTML:
            fail(f"missing sheet element #{el}")
ok("both sheet layers present")


# --- 2. the hidden attribute must win --------------------------------------

if re.search(r"\[hidden\]\s*\{[^}]*display\s*:\s*none\s*!important", CSS, re.S):
    ok("global [hidden] { display: none !important } present")
else:
    fail(
        "no global [hidden] { display: none !important } rule - any component "
        "styled with `display` will ignore the hidden attribute and cover the app"
    )

hidden_els = re.findall(r'<[^>]*\bid="([^"]+)"[^>]*\bclass="([^"]*)"[^>]*\bhidden\b', HTML)
display_classes = {
    cls
    for cls, body in re.findall(r"\.([\w-]+)\s*\{([^}]*)\}", CSS)
    if re.search(r"(^|;)\s*display\s*:", body)
}
at_risk = [
    (el_id, cls)
    for el_id, classes in hidden_els
    for cls in classes.split()
    if cls in display_classes
]
if at_risk:
    listed = ", ".join(f"#{i} (.{c})" for i, c in at_risk)
    ok(f"{len(at_risk)} hidden element(s) rely on that rule: {listed}")
else:
    ok("no hidden element sets display via a class")


# --- 3. every configured screen exists -------------------------------------

tab_ids = re.findall(r"\{\s*id:\s*'([^']+)'\s*,\s*label:\s*'[^']*',\s*icon:", CONFIG)
extra = re.search(r"extraScreens:\s*\[([^\]]*)\]", CONFIG)
extra_ids = re.findall(r"'([^']+)'", extra.group(1)) if extra else []

orphans = [t for t in tab_ids + extra_ids if f'id="screen-{t}"' not in HTML]
if orphans:
    fail(f"config declares screens with no section in index.html: {', '.join(orphans)}")
else:
    ok(f"all {len(tab_ids) + len(extra_ids)} configured screen(s) exist in index.html")


# --- 4. version strings agree ----------------------------------------------

def norm(match: re.Match | None) -> str | None:
    """Normalize a version string, tolerating a leading 'v'."""
    return match.group(1).lstrip("v") if match else None


vals = {
    "config.js version": norm(re.search(r"version:\s*'([^']+)'", CONFIG)),
    "sw.js CACHE_VERSION": norm(re.search(r"CACHE_VERSION\s*=\s*'([^']+)'", SW)),
    "version.json version": norm(
        re.search(r'"version"\s*:\s*"([^"]+)"', (HERE / "version.json").read_text())
    ),
}
if len(set(vals.values())) == 1 and None not in vals.values():
    ok(f"version strings agree ({vals['config.js version']})")
else:
    fail(f"version strings disagree: {vals} - updates will not install cleanly")


# --- 5. every module is precached ------------------------------------------

modules = {p.name for p in HERE.glob("*.js") if p.name != "sw.js"}
precached = set(re.findall(r"'\./([\w.-]+)'", SW))
missing_pre = sorted(m for m in modules if m not in precached)
if missing_pre:
    fail(f"sw.js PRECACHE is missing: {', '.join(missing_pre)} - offline will break")
else:
    ok(f"all {len(modules)} JS modules are precached")


print()
if failures:
    print(f"{len(failures)} FAILURE(S)")
    sys.exit(1)
print("ALL UI CHECKS PASSED")
